-- ------------------------------------
USE `BachecaElettronicadb`
-- ------------------------------------

call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 130, null, 'sigkreco', 'Videogames');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'sigkreco', 'Elettrodomestici');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 250, null, 'dottbo', 'Telefonia');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 200, null, 'dottbo', 'Bici');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 300, null, 'fioreeri', 'Fai da te');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 100, null, 'fioreeri', 'Moto');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 300, null, 'dottmeco', 'Telefonia');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 200, null, 'dottmeco', 'Accessori');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 130, null, 'gianatti', 'Moto');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 250, null, 'gianatti', 'Motori');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 200, null, 'zelidando', 'Sport');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 20, null, 'zelidando', 'Telefonia');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 50, null, 'marisri', 'Informatica computer');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 100, null, 'marisri', 'Auto');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 200, null, 'dotteli', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 250, null, 'dotteli', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 100, null, 'dottmnti', 'Bici');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 250, null, 'dottmnti', 'Informatica computer');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 350, null, 'shaino', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 200, null, 'shaino', 'Informatica computer');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 90, null, 'marceosa', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 300, null, 'marceosa', 'Informatica computer');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 100, null, 'marianco', 'Elettronica');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 130, null, 'marianco', 'Abbigliamento');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'karimmina', 'Motori');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 250, null, 'karimmina', 'Telecomunicazioni');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 130, null, 'sigprzo', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 400, null, 'sigprzo', 'Motori');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 90, null, 'drrusso', 'Sport');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 90, null, 'drrusso', 'Informatica computer');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 300, null, 'elgarosi', 'Elettronica');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 400, null, 'elgarosi', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 350, null, 'drtomssi', 'Moto');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 300, null, 'drtomssi', 'Telefonia');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 200, null, 'dottbri', 'Orologi e gioielli');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 90, null, 'dottbri', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 100, null, 'cirarizo', 'Elettronica');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 90, null, 'cirarizo', 'Telefonia');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 350, null, 'ingvitno', 'Sport');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 100, null, 'ingvitno', 'Sport');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 250, null, 'drgiulri', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 200, null, 'drgiulri', 'Locali Commerciali');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'demirra', 'Telefonia');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 200, null, 'demirra', 'Elettronica');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'ritamoti', 'Accessori');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 300, null, 'ritamoti', 'Moto');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'ingaina', 'Locali Commerciali');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 50, null, 'ingaina', 'Motori');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 400, null, 'concci', 'Telefonia');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 350, null, 'concci', 'Locali Commerciali');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 300, null, 'cirinoco', 'Informatica computer');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 400, null, 'cirinoco', 'Motori');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 100, null, 'dindocmbo', 'Orologi e gioielli');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 130, null, 'dindocmbo', 'Orologi e gioielli');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 200, null, 'odonebri', 'Videogames');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 50, null, 'odonebri', 'Telecomunicazioni');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 350, null, 'ferdndo', 'Sport');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 20, null, 'ferdndo', 'Sport');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 300, null, 'concetta', 'Elettrodomestici');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 130, null, 'concetta', 'Moto');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 250, null, 'guidocte', 'Moto');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 100, null, 'guidocte', 'Informatica computer');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'fulviino', 'Sport');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 300, null, 'fulviino', 'Accessori');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 250, null, 'lisalli', 'Informatica computer');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 130, null, 'lisalli', 'Elettronica');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 90, null, 'dottloara', 'Abbigliamento');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'dottloara', 'Accessori');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 130, null, 'flaviadi', 'Auto');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 50, null, 'flaviadi', 'Sport');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 300, null, 'bibialia', 'Bici');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 100, null, 'bibialia', 'Orologi e gioielli');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 90, null, 'karito', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 200, null, 'karito', 'Motori');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'ritadati', 'Videogames');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 20, null, 'ritadati', 'Informatica computer');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 20, null, 'drkayri', 'Abbigliamento');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 200, null, 'drkayri', 'Abbigliamento');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 400, null, 'ruthrici', 'Abbigliamento');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'ruthrici', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 50, null, 'samuesso', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'samuesso', 'Auto');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 20, null, 'dottmti', 'Videogames');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 90, null, 'dottmti', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'dottaini', 'Elettronica');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 100, null, 'dottaini', 'Videogames');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 90, null, 'sigmsta', 'Elettrodomestici');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 130, null, 'sigmsta', 'Elettrodomestici');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 350, null, 'dottari', 'Sport');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 400, null, 'dottari', 'Locali Commerciali');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 350, null, 'ingridelo', 'Telefonia');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 130, null, 'ingridelo', 'Telecomunicazioni');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 50, null, 'baldco', 'Elettronica');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 350, null, 'baldco', 'Motori');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'luigile', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 250, null, 'luigile', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 350, null, 'morgara', 'Bici');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 90, null, 'morgara', 'Auto');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 20, null, 'drrenna', 'Elettrodomestici');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 130, null, 'drrenna', 'Orologi e gioielli');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 90, null, 'sigarneo', 'Informatica computer');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 50, null, 'sigarneo', 'Elettrodomestici');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 200, null, 'ceccolo', 'Motori');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 50, null, 'ceccolo', 'Locali Commerciali');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 250, null, 'ritano', 'Abbigliamento');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 400, null, 'ritano', 'Bici');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 50, null, 'ingediero', 'Orologi e gioielli');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 20, null, 'ingediero', 'Orologi e gioielli');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 100, null, 'cleopana', 'Orologi e gioielli');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 100, null, 'cleopana', 'Fai da te');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 100, null, 'raniri', 'Fai da te');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'raniri', 'Elettronica');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 90, null, 'ingnoadi', 'Abbigliamento');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'ingnoadi', 'Accessori');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 90, null, 'dotteti', 'Videogames');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 250, null, 'dotteti', 'Accessori');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 300, null, 'oseaneri', 'Moto');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 100, null, 'oseaneri', 'Abbigliamento');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 350, null, 'edilioni', 'Auto');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 400, null, 'edilioni', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 90, null, 'ingtreri', 'Abbigliamento');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 350, null, 'ingtreri', 'Locali Commerciali');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 100, null, 'sigrrdo', 'Elettronica');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 90, null, 'sigrrdo', 'Bici');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 300, null, 'pablomlli', 'Locali Commerciali');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 130, null, 'pablomlli', 'Elettronica');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'drsiti', 'Fai da te');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 200, null, 'drsiti', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 250, null, 'priamoro', 'Abbigliamento');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'priamoro', 'Informatica computer');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 50, null, 'drconctti', 'Informatica computer');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 90, null, 'drconctti', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 50, null, 'silvaas', 'Bici');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 20, null, 'silvaas', 'Telecomunicazioni');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 20, null, 'concdi', 'Locali Commerciali');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 350, null, 'concdi', 'Locali Commerciali');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 130, null, 'sigrti', 'Telecomunicazioni');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 400, null, 'sigrti', 'Auto');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'ruthnna', 'Telecomunicazioni');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 100, null, 'ruthnna', 'Moto');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 400, null, 'cassiali', 'Fai da te');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 300, null, 'cassiali', 'Motori');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 100, null, 'donaeco', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'donaeco', 'Moto');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'dindoso', 'Fai da te');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 20, null, 'dindoso', 'Telecomunicazioni');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 130, null, 'naomiini', 'Elettronica');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 90, null, 'naomiini', 'Moto');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 90, null, 'dylano', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 300, null, 'dylano', 'Sport');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 200, null, 'inggali', 'Informatica computer');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 20, null, 'inggali', 'Elettrodomestici');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 300, null, 'erminissi', 'Accessori');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 50, null, 'erminissi', 'Auto');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'drjacana', 'Elettrodomestici');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 350, null, 'drjacana', 'Sport');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 20, null, 'gerlanisi', 'Locali Commerciali');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 90, null, 'gerlanisi', 'Motori');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 400, null, 'arieri', 'Informatica computer');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 100, null, 'arieri', 'Accessori');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 50, null, 'dottrotti', 'Telecomunicazioni');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 90, null, 'dottrotti', 'Videogames');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 300, null, 'ireneari', 'Accessori');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 400, null, 'ireneari', 'Auto');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 250, null, 'marusksi', 'Elettrodomestici');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 300, null, 'marusksi', 'Moto');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 350, null, 'fiorla', 'Abbigliamento');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 400, null, 'fiorla', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 250, null, 'oseagssi', 'Telefonia');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 20, null, 'oseagssi', 'Sport');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 300, null, 'dralni', 'Sport');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 20, null, 'dralni', 'Videogames');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 200, null, 'eustazo', 'Orologi e gioielli');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 50, null, 'eustazo', 'Abbigliamento');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 200, null, 'dottfano', 'Motori');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 250, null, 'dottfano', 'Telecomunicazioni');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 130, null, 'zelidani', 'Immobili');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 250, null, 'zelidani', 'Videogames');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'ingmtti', 'Informatica computer');
call BachecaElettronicadb.inserimentoNuovoAnnuncio('Descrizione: descrizione di default', 150, null, 'ingmtti', 'Locali Commerciali');
